### ISSUE TITLE
Smileys hinzufügen

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#22]
Man soll zu jeder Antwort des Chatbots passende Smileys hinzufügen, um sie freundlicher und motivierender zu machen.

**Comment by MariiaVerbovets** [comment]
habe ich gemacht. @johanna-fischer  magst es checken bitte?

**Comment by johanna-fischer** [comment]
Ja passt da sind jetzt auch alle Lücken die wir hatten geschlossen
