### ISSUE TITLE
Fehlermeldung umsetzen

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#23]
Probier so zu machen, dass der Chatbot, wenn er die Frage nicht versteht oder nicht genug Infos hat, sowas antwortet "Sorry, aber ich habe dich nicht verstanden. Lass meine Programmierer deine Anfrage bearbeiten. Vielleicht kann ich dir beim nächsten Mal helfen."

**Comment by MariiaVerbovets** [comment]
Done ✅
Johanna, kannst du es bitte ausprobieren?
Er soll schreiben, dass er dich nicht versteht, wenn du etwas fragst, was er noch nicht erkennen kann.

**Comment by MariiaVerbovets** [comment]
Johanna, kannst du es bitte ausprobieren?
Er soll schreiben, dass er dich nicht versteht, wenn du etwas fragst, was er noch nicht erkennen kann.

**Comment by johanna-fischer** [comment]
Hab es getestet, läuft alles :)
