### ISSUE TITLE
3 Videos finden (Thema: Aufwärmen)

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#26]
Man soll auf YouTube 3 Videos mit Aufwärmen-Übungen finden und die embed Links in die Tabelle hinzufügen.
https://docs.google.com/document/d/16tZ4MShbxwni3AIyg88I6ijiRjkvwA6dfX4YChkxgTY/edit?usp=sharing

**Comment by simonzass** [comment]
Ich habe 3 Videos mit Übungen zum Aufwärmen hinzugefügt.

**Comment by MariiaVerbovets** [comment]
Super, danke👍🏻
