### ISSUE TITLE
Code schreiben (Thema: Kardiotraining)

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#28]
Man soll für seine 3 Videos einen Code (intent, actions (links zu Videos)) bei sich am Laptop lokal schreiben und ihn (nach rasa train und checken, ob er funktioniert) dann pushen.

Im Terminal:
rasa train
rasa shell (chattet mit dem Chatbot und prüft, ob er das Thema, das ihr entwickelt habt, bearbeiten kann und auf die fragen antworten kann)

wenn es funktioniert:
git add .
git commit -m "added ein paar Videos für Kardio"
git push

**Comment by johanna-fischer** [comment]
Hey Mariia kannst du bitte drüber schauen ob der Code so passt und funktioniert?

**Comment by MariiaVerbovets** [comment]
Wo finde ich den Code eigentlich? :D

**Comment by johanna-fischer** [comment]
Müsste eigentlich schon gepusht sein :)

**Comment by MariiaVerbovets** [comment]
ich habe einen kleinen Fehler gefixt und pushe es gleich

**Comment by johanna-fischer** [comment]
Perfekt :)
