### ISSUE TITLE
Code schreiben (Thema: Aufwärmen)

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#29]
Man soll für seine 3 Videos einen Code (intent, actions (links zu Videos)) bei sich am Laptop lokal schreiben und ihn (nach rasa train und checken, ob er funktioniert) dann pushen.

Im Terminal:
rasa train
rasa shell (chattet mit dem Chatbot und prüft, ob er das Thema, das ihr entwickelt habt, bearbeiten kann und auf die fragen antworten kann)

wenn es funktioniert:
git add .
git commit -m "added ein paar Videos für Aufwärmen"
git push

**Comment by MariiaVerbovets** [comment]
<img width="952" alt="Screenshot 2022-12-15 at 21 27 15" src="https://user-images.githubusercontent.com/116882226/207960123-492192f1-8789-4695-b71a-6e1815b894b6.png">

hier bitte Beispiele zu Yoga schreiben

**Comment by MariiaVerbovets** [comment]
<img width="840" alt="Screenshot 2022-12-15 at 21 27 54" src="https://user-images.githubusercontent.com/116882226/207960238-6f9333e7-0ad8-434b-84f0-4beea05b6114.png">

hier deine Video-links

**Comment by MariiaVerbovets** [comment]
<img width="1180" alt="Screenshot 2022-12-15 at 21 28 24" src="https://user-images.githubusercontent.com/116882226/207960334-e4d3e52b-924c-4e7b-9058-2c97ee619d16.png">

und hier mehr Beispiele bitte

**Comment by simonzass** [comment]
Habe die Aufwärmübungen sowie Beispiele zum Code hinzugefügt und gepushed.

**Comment by johanna-fischer** [comment]
Perfekt läuft alles :)
