### ISSUE TITLE
Neue Stories entwickeln (Mariia)

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#30]
Man soll einen Code (intents, responses, stories) für verschiedene Anfragen des Nutzers entwickeln.

Was soll der Chatbot auf die Fragen wie "Was ist 1+1", "Kannst du mir ein Theater empfehlen?" oder "Wer ist der Präsident von Amerika?" usw. antworten? Überleg dir, welche Fragen der Nutzer stellen könnte und lass deinen Chatbot sie freundlich und vielleicht auch mit Humor (und Smileys) beantworten.

Mehr Details auf Google Drive:
https://docs.google.com/document/d/1gOAGe08NuRZX-aIieUobkpgvnXmlkGbdra0otMAYQg0/edit?usp=sharing

**Comment by MariiaVerbovets** [comment]
1. Ich habe 3 Actions zu Videovorschläge, einige Stories dazu und ein paar Listen mit responses in actions.py geschrieben.

**Comment by MariiaVerbovets** [comment]
Ich habe noch gemacht, dass der Chatbot auf die folgenden Fragen antworten kann:
-Wie alt bist du?
-Woher kommst?
-Hast du eine Familie?
-Was ist dein Job?

**Comment by MariiaVerbovets** [comment]
@KatharinaBreunig magst du es checken?

**Comment by MariiaVerbovets** [comment]
<img width="350" alt="Screenshot 2022-12-15 at 21 59 27" src="https://user-images.githubusercontent.com/116882226/207965988-baaa7550-cdf8-4639-8da4-834b18ef9f7d.png">

<img width="354" alt="Screenshot 2022-12-15 at 21 59 35" src="https://user-images.githubusercontent.com/116882226/207965999-e016b0d0-802b-41d6-978c-b77efa028b41.png">

**Comment by johanna-fischer** [comment]
Passt, ich mach dann das Issue zu
