### ISSUE TITLE
Neue Stories entwickeln (Johanna)

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#32]
Man soll einen Code (intents, responses, stories) für verschiedene Anfragen des Nutzers entwickeln.

Was soll der Chatbot auf die Fragen wie "Was ist 1+1", "Kannst du mir ein Theater empfehlen?" oder "Wer ist der Präsident von Amerika?" usw. antworten? Überleg dir, welche Fragen der Nutzer stellen könnte und lass deinen Chatbot sie freundlich und vielleicht auch mit Humor (und Smileys) beantworten.

Mehr Details auf Google Drive:
https://docs.google.com/document/d/1gOAGe08NuRZX-aIieUobkpgvnXmlkGbdra0otMAYQg0/edit?usp=sharing

**Comment by johanna-fischer** [comment]
Ideen

- Witze einbauen wenn danach gefragt wird (sportbezogen)
- Flüssigkeitsbedarf berechnen

**Comment by johanna-fischer** [comment]
Also die Umsetzung bekomm ich nichtmehr hin. Bin ziemlich lang am Design gesessen :/
