### ISSUE TITLE
Review nach Sprint 1

### ISSUE THREAD

**Issue by johanna-fischer** [ID-Start-Winter22/chat-team-3#34]
Man soll eine Wiki-Seite und eine PDF-Datei (Design Teil) machen, über den aktuellen Forschungsstand des Projektmoduls.

**Comment by MariiaVerbovets** [comment]
Ich habe auf der Wiki Seite im 'Teil Design' (1. Look&Feel, 2. Kurze Geschichte, 3. Conversation Design Canvas und Worksheet, 4. Dialoge) und Teil Informatik erledigt ✅

**Comment by johanna-fischer** [comment]
Ich hab noch diesen Punkt ergänzt:
Entwickeln Sie eine kurze Geschichte über den Bot, analog zu einer Figur aus einem Spielfilm oder Theaterstück.

**Comment by johanna-fischer** [comment]
PDF ist jetz auch auf der Wiki

**Comment by MariiaVerbovets** [comment]
done
