### ISSUE TITLE
Prototyp an Leihen testen 

### ISSUE THREAD

**Issue by johanna-fischer** [ID-Start-Winter22/chat-team-3#35]
Jeder von uns soll bitte mal den Chatbot, nur mit der Vorinformation das es ein "Fitnessbot" ist der Videos ausgeben kann, an Freunden, Bekannten, Komilitonen usw. austesten und notieren welche Fragen sich ergeben haben die der Bot nicht beantworten kann.

**Comment by johanna-fischer** [comment]
Ich kann den Prototyp erst kommendes Wochenende an Personen testen. Schau auch das ich eine möglichst hohe Altersspanne erreiche. Wär super wenn jeder so übers Wochenende testen könnte und hier kurz schreiben könnte, was unbedingt noch mit rein muss in den Chatbot.

**Comment by MariiaVerbovets** [comment]
Johanna, wie soll ich die Datei auf Google Drive nennen?

**Comment by johanna-fischer** [comment]
Softwaretest an Leihen

**Comment by MariiaVerbovets** [comment]
Done: https://docs.google.com/document/d/12ii7rRH8nv7rjInhbVCPvWz8-OFknVREMgjKBDFDoxw/edit

**Comment by johanna-fischer** [comment]
Das haben wir ja jetzt auf Miro unter Usability Testing, dann schließ ich das mal dann ist wieder aufgeräumt :)
