### ISSUE TITLE
Code schreiben (Thema: Yoga)

### ISSUE THREAD

**Issue by KatharinaBreunig** [ID-Start-Winter22/chat-team-3#37]
Man soll für seine 3 Videos einen Code (intent, actions (links zu Videos)) bei sich am Laptop lokal schreiben und ihn (nach rasa train und checken, ob er funktioniert) dann pushen.

Im Terminal:
rasa train
rasa shell (chattet mit dem Chatbot und prüft, ob er das Thema, das ihr entwickelt habt, bearbeiten kann und auf die fragen antworten kann)

wenn es funktioniert:
git add .
git commit -m "added ein paar Videos für Yoga, changed domain, nly, stories"
git push

**Comment by MariiaVerbovets** [comment]
<img width="956" alt="Screenshot 2022-12-15 at 21 24 20" src="https://user-images.githubusercontent.com/116882226/207959722-e0a8f962-608b-42e8-bea1-634fe17638c2.png">

hier bitte Beispiele zu Yoga schreiben

**Comment by MariiaVerbovets** [comment]
<img width="733" alt="Screenshot 2022-12-15 at 21 25 57" src="https://user-images.githubusercontent.com/116882226/207959892-894afe08-027f-425a-8e27-9a6195a106c2.png">

hier Video-links rein bitte

**Comment by MariiaVerbovets** [comment]
<img width="1138" alt="Screenshot 2022-12-15 at 21 26 31" src="https://user-images.githubusercontent.com/116882226/207959993-56f384a3-315b-4992-9538-81fcb228024e.png">


mehr Beispiele dazu

**Comment by johanna-fischer** [comment]
Yoga ist jetzt schon implementiert?

**Comment by MariiaVerbovets** [comment]
Ja, ich habe es gemacht
