### ISSUE TITLE
Ideensammlung und Implementierung (Buttons)

### ISSUE THREAD

**Issue by simonzass** [ID-Start-Winter22/chat-team-3#39]
Jeder sammelt Ideen, in welchen Fällen wir Buttons in den Chatbot einbauen können. (Bei welchen Nachrichten des Bots sind Buttons als Antwortmöglichkeit sinnvoll?)
https://docs.google.com/document/d/1nxXBT1Zq8t2Pe0kj2R4DydqUNp-Exp9az2wNoJlFTg8/edit

**Comment by johanna-fischer** [comment]
Vielleicht wären Buttons sinnvoll, wenn wir die Fitnesstudios einbauen. Man könnte z.B. eine Auswahl geben "Billig"; "Beste Ausstattung"; "Beste Betreuung"

**Comment by MariiaVerbovets** [comment]
Hey Leute,
ich habe Buttons hinzugefügt bei:
- what_can_you_do intent
- Gymsuche

<img width="362" alt="Screenshot 2023-01-12 at 22 18 08" src="https://user-images.githubusercontent.com/116882226/212198119-8afeec53-6df2-41bf-94f2-e29dd3078288.png">

<img width="368" alt="Screenshot 2023-01-12 at 22 17 49" src="https://user-images.githubusercontent.com/116882226/212198107-300b380f-7295-4b21-8b02-c26ecd0301ac.png">


Checkt es gerne und gebt mir bitte Feedback ;)

**Comment by MariiaVerbovets** [comment]
@simonzass  wie sieht es mit deinen Buttons bei Kalorienbedarfrechner aus? ;)

**Comment by johanna-fischer** [comment]
Das passt alles hab gesehen der von @simonzass ist auch implementiert
