### ISSUE TITLE
Digitales Zuhause (Creative Vision)

### ISSUE THREAD

**Issue by simonzass** [ID-Start-Winter22/chat-team-3#46]
Für den Chatbot soll ein digitales Zuhause, z.B. in Form einer Page / Poster erstellt werden.

**Comment by johanna-fischer** [comment]
Oh wir haben das Issue irgendwie doppelt ich mach mal das alte zu :)

**Comment by johanna-fischer** [comment]
Bzw. war das noch auf das Icon und so bezogen.

**Comment by johanna-fischer** [comment]
Ich habe jetzt verschiedene Designs gemacht, kann sie nur hier nicht hochladen weil die Datei zu groß ist. Am Besten schauen wir morgen die gemeinsam mal durch :)

**Comment by MariiaVerbovets** [comment]
Du kannst gerne Screenshots schicken ;)

**Comment by johanna-fischer** [comment]
Das war das Endergebnis für das Digitale Zuha
![background_kanguru](https://user-images.githubusercontent.com/116874994/213816489-b5aa83d3-3ba4-40ce-ba2f-f8c9c53f7aa7.png)
use

**Comment by johanna-fischer** [comment]
Gibt auch eine Handy angepasste Version müssen wir nur mal schauen ob das dann auch sicher gut ausschaut.
Auch der Chatbot sollte dann von der breite her komplett sichtbar sein, am Handy.

**Comment by johanna-fischer** [comment]
Das Digitale Zuhause ist jetzt auch auf der Wiki Seite unten bei Design zu finden

**Comment by johanna-fischer** [comment]
@KatharinaBreunig magst du bitte schauen ob alles so passt ?

**Comment by MariiaVerbovets** [comment]
@johanna-fischer  es passt, danke
