### ISSUE TITLE
Berechnung BMI

### ISSUE THREAD

**Issue by johanna-fischer** [ID-Start-Winter22/chat-team-3#48]
Evtl implementieren von der Option, den BMI zu berechnen.

**BMI=kg/m2**

<html><body>

Gewichtsklasse | BMI | BMI
-- | -- | --
  | Frauen | Männer
Untergewicht | unter 17,5 | unter 18,5
Normalgewicht | 17,5–24 | 18,5–24
Übergewicht, Präadipositas | 25–29 | 25–29
Starkes Übergewicht,Adipositas, Fettleibigkeit | 30–35 | 30–35

</body>
</html>

**Comment by MariiaVerbovets** [comment]
haben im Team erledigt ✅
