### ISSUE TITLE
Berechnung Kalorienbedarf

### ISSUE THREAD

**Issue by johanna-fischer** [ID-Start-Winter22/chat-team-3#49]
Evtl implementieren von der Option, den Kalorienbedarf zu berechnen.

Körpergewicht * 35 ml

ab 65 Jahren
Körpergewicht * 30 ml

**Grundumsatz:**
Männer: RMR = (10 × Gewicht in kg) + (6,25 × Größe in cm) – (5 × Alter) + 5
Frauen: RMR = (10 × Gewicht in kg) + (6,25 × Größe in cm) – (5 × Alter) – 161

**Aktivitätsfaktor festlegen:**
<html><body>

Aktivitätslevel | Beschreibung | Faktor
-- | -- | --
wenig aktiv | kein oder wenig Training, überwiegend sitzende Tätigkeit | 1,2
leicht aktiv | leichtes Training / Sport an 1-3 Tagen pro Woche | 1,375
moderat aktiv | moderates Training / Sport an 3-5 Tagen pro Woche | 1,55
sehr aktiv | anstrengendes Training / Sport an 6-7 Tagen pro Woche | 1,725
extrem aktiv | anstrengendes tägliches Training / Sport, Leistungssport, harte körperliche Arbeit oder 2x tägliches Training | 1,9

</body>
</html>

**Täglichen Kalorienbedarf berechnen:**
Kalorienbedarf = RMR × Aktivitätsfaktor

**Comment by simonzass** [comment]
Ich habe jetzt schon mal eine erste Version vom Kalorienbedarf Rechner in meinen branch (Simon) gepushed. Bitte schaut ihn euch an, ob ihr Fehler findet oder Feedback habt. Wenn alles passt, füge ich ihn in den main branch hinzu.

**Comment by MariiaVerbovets** [comment]
Hey Simon. Ich habe es getestet. Manchmal erkennt er das Geschlecht nicht, deswegen habe ich mehr Examples geschrieben (auf Simon branch). Dann ging's! Magst du noch den Faktor hinzufügen? Wie es in der Tabelle steht? 🤓

**Comment by MariiaVerbovets** [comment]
Hey Simon.
Ich habe es bei einem Freund getestet, er meinte es ist falsch, was der Chatbot berechnet hat (viel zu wenige Kalorien).
Du hast den Faktor vergessen. Es ist wichtig :)
Machst du es noch bitte?

**Comment by simonzass** [comment]
Hey Mariia,
Falsch ist es nicht, da aktuell der Grundumsatz an Kalorien berechnet wird. Auch im Chatbot und im Code ist die Rede von Kaloriengrundumsatz, das ist schon beabsichtigt, damit kein Missverständnis entsteht. Mit dem Faktor ist es dann der tägliche Kalorienbedarf. Natürlich füge ich den Faktor aber noch hinzu, das habe ich eh noch vor, keine Sorge ;)

**Comment by johanna-fischer** [comment]
Also soweit läuft er ja @simonzass ist der Faktor jetzt schon implementiert wenn nicht ist es ja auch nicht schlimm. Da ja die Grundfunktion da ist und kann ja dann noch erweitert werden. Aber bitte nichtsmehr kurz vor Freitag machen, weil uns sonst die Zeit fehlt zum reparieren :)

**Comment by MariiaVerbovets** [comment]
Ich habe den Faktor implementiert und pushe es gleich 👌🏻
