### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#53]
Code für Welcome-Nachricht schreiben, damit der Chatbot dich am Anfang begrüßt

**Comment by MariiaVerbovets** [comment]
Ich habe es erledigt und gepusht. @simonzass check bitte, ob er dich am Anfang des Gespräches begrüßt

**Comment by johanna-fischer** [comment]
Ich hab die schonmal angeschaut, bei mir geht das. Find auch gut das man gleich sieht was unser Chatbot alles kann.
