### ISSUE TITLE
Action Gymsuche -> Links dynamisch machen

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#54]
Links von Action Gymsuche sollen im Chat clickable sein

**Comment by MariiaVerbovets** [comment]
Ich habe es erledigt und gepusht. @simonzass check bitte, ob bei der Gymsuche (Altstadt - jedes Kriterium außer Lokation geht) die Links von Gyms clickable sind. Danke :)

**Comment by johanna-fischer** [comment]
Klappt bei mir auch, hab die Funktion jetzt auch mal in da Präsi im Design aufgegriffen aber da sprechen wir uns einfach nächste Woche ab, damit ihr genau wisst was ich da meine :)
