### ISSUE TITLE
Design PDF erstellen 

### ISSUE THREAD

**Issue by johanna-fischer** [ID-Start-Winter22/chat-team-3#56]

**Comment by johanna-fischer** [comment]
Hey ich hab auf der Wiki Seite unten beim Design Teil die PDF Datei hinterlegt bitte mal alle drüber schauen ob die so passt. Würd vorschlagen das wir die ziemlich so wie die ist auch in der Abschlusspräsentation verwenden. Können gerne noch was ergänzen oder abändern, wenn gewünscht :)

**Comment by MariiaVerbovets** [comment]
Deine PDF-Datei zum Design Teil finde ich gut, aber sie als Präsentation für 27.01 würde ich nicht nehmen...hier ist doch nur Design Teil und nicht ganz (Stake Holder Map, Usability Tests sind z.B. nicht da).

Ich würde für Freitag etwas kürzeres, aber auch mit Recherchen, Prozessen usw. machen, dass wir den Prozess und die Idee besser präsentieren, nicht nur das Design. Vllt das auch in Figma machen, um es interaktiver darzustellen 🤔

Ich schaue mir die Aufgabe am Wochenende genauer an

**Comment by johanna-fischer** [comment]
Ja können wir auch machen, allgemein wäre gut wenn wir uns kommende Woche mal zusammen setzten könnten, um unsere Abschlusspräsentation durch zu gehen. Vielleicht könnten wir da auch das in Figma alle gemeinsam machen und jeder einbringen was für die Präsentation wichtig wäre.
