### ISSUE TITLE
Mobile Design responsive 

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#57]
Man soll das Design für Handys responsive machen (je nachdem welche Bildschirmgröße das Handy hat sollen sich die Elemente schieben)

**Comment by MariiaVerbovets** [comment]
erledigt
@johanna-fischer magst du es testen bitte? :)

**Comment by johanna-fischer** [comment]
So hab jetzt nochmal alles final geprüft für morgen, sieht alles super aus :)
