### ISSUE TITLE
Abschlusspräsentation

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#58]
Jeder macht sein Teil für die Präsentation (27.01)
https://docs.google.com/presentation/d/18HTKB52Kn4_xTmxOec8IsVYt111pBFP-2UiX0wlW6e0/edit?usp=sharing

**Comment by MariiaVerbovets** [comment]
mein Teil der Präsentation ist schon fertig

**Comment by johanna-fischer** [comment]
Mein Teil ist nochmal überarbeitet und drinnen bin den jetzt nochmal durch gegangen sollte alles so logisch sein vom Aufbau her

**Comment by MariiaVerbovets** [comment]
erledigt
