### ISSUE TITLE
Icon und Hintergrund weiter entwickeln 

### ISSUE THREAD

**Issue by MariiaVerbovets** [ID-Start-Winter22/chat-team-3#8]
Jeder macht mindestens ein Icon bis 24.11

**Comment by MariiaVerbovets** [comment]
<img width="1440" alt="Screenshot 2022-12-08 at 22 34 14" src="https://user-images.githubusercontent.com/116882226/206573650-0e0bc683-8970-4260-9129-38d65aededa9.png">

Wie findet ihr das? :)

**Comment by johanna-fischer** [comment]
Hey ich hab neue Designs für den Hintergrund gemacht, leider kann ich die hier nicht hochladen. Ich zeig sie euch morgen :)
